### ISSUE TITLE
Getting "The process priority MUST not be changed" error repeatedly despite not changing it

### ISSUE THREAD

**Issue by ghost** [GodotNetworking/example-project#5]
After a lot of debugging and taking some code from [a pull request](https://github.com/GodotNetworking/example-project/pull/4), I finally got rid of all of the errors that the editor could catch. However, when I finally tested the game, I saw this:

![image](https://github.com/GodotNetworking/example-project/assets/85314434/d2e081f5-4be9-4d97-8468-2a329fe54e69)

I tried many things to get it working, even did CTRL+F on every script to make sure it wasn't changing the process priority, but nothing worked. I am not sure whether this is a module issue or a project issue. Is there any way to find what is wrong?

Note: I am on the latest unstable version of Godot but that is likely not the issue, as I haven't had any compatibility issues on unstable before.

**Comment by ghost** [comment]
Didn't find the issue but something is probably just set up wrong. Already managed to make a functional project somewhere else so I'll just close this.

**Comment by AndreaCatania** [comment]
Oh great! Please let me know if you need any assistance.
